### ISSUE TITLE
Create a pretty 404 error page

### ISSUE THREAD

**Issue by darthtrevino** [atsid/www.atsid.com#17]
We can configure the S3 static hosting to redirect to a custom error page.  We can probably do better than this:
![screen shot 2015-07-29 at 11 09 44 am](https://cloud.githubusercontent.com/assets/113544/8965760/55c53e5c-35e2-11e5-9f5d-00c70dc3391d.png)

**Comment by bmathews** [comment]
@darthtrevino Can you set it redirect to `/404/`?
