### ISSUE TITLE
Responsive behavior of images on Career Page

### ISSUE THREAD

**Issue by TereseV** [atsid/www.atsid.com#31]
It looks okay horizontally, but vertically a bit too small. Should we just get rid of it for mobile? 

![img_7835](https://cloud.githubusercontent.com/assets/12399802/9413188/72892606-47fe-11e5-8440-f7d7bb61b246.PNG)

**Comment by bingles** [comment]
Ben and I were chatting about this yesterday and we'll narrow it down to a main image for this section

**Comment by TereseV** [comment]
Cool :-)
