### ISSUE TITLE
Job Openings

### ISSUE THREAD

**Issue by TereseV** [atsid/www.atsid.com#32]
The spacing on the vertical screen is cramped. Looks good horizontally though. Can we stack it more for vertical? 

![img_7836](https://cloud.githubusercontent.com/assets/12399802/9413240/ade658e0-47fe-11e5-8522-d23e75978ffd.PNG)
![img_7837](https://cloud.githubusercontent.com/assets/12399802/9413239/ade6629a-47fe-11e5-92fb-4f6b8f3d6985.PNG)

**Comment by Luckyshot101** [comment]
Was this fixed @bingles ?  Just wanting to close the issue if it was.

**Comment by bingles** [comment]
Yup, verified on iPhone 5s
