### ISSUE TITLE
:-/

### ISSUE THREAD

**Issue by TereseV** [atsid/www.atsid.com#34]
<img width="1281" alt="screen shot 2015-09-23 at 5 00 19 pm" src="https://cloud.githubusercontent.com/assets/12399802/10058736/0b23524e-6215-11e5-8f75-d9ecdb80184c.png">

**Comment by TereseV** [comment]
@bingles

**Comment by bingles** [comment]
LOL...this is probably the best issue I have EVER seen! Sadly (for you), this image is too perfect!

**Comment by natoverse** [comment]
:+1:

**Comment by TereseV** [comment]
Eek! So there is a real defect on this page. But I didn't even notice it prior. David just pointed out the period and exclamation point.

**Comment by Ken-2scientists** [comment]
Fixed the punctuation issue with commit d70f528adde62949335ac6a417cfcbb97dc22e25
