### ISSUE TITLE
404 errors redirect to atsid.net instead of atsid.com

### ISSUE THREAD

**Issue by Ken-2scientists** [atsid/www.atsid.com#52]
Developer tools console shows the following error logged:

```
Mixed Content: The page at 'https://www.atsid.com/careers/' was loaded over HTTPS, but requested an insecure font 'http://www.atsid.net/404'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by bmathews** [comment]
It looks like any 404 is being redirected to atsid.net.  So the missing font file gets redirected to that. 

E.g., www.atsid.com/zzzz.png

**Comment by bmathews** [comment]
Glad to see it live! :tada: :tada:  :tada:  :tada:  :tada:

**Comment by Ken-2scientists** [comment]
Okay, I traced this down to the S3 bucket configuration. Within those S3 bucket configs, 404 errors are coded to redirect to the 404 page on `stage.atsid.net` and `www.atsid.net` respectively.

**Comment by Ken-2scientists** [comment]
Resolved via manual change to S3 bucket configuration via AWS Console
