### ISSUE TITLE
Fix travis deployments

### ISSUE THREAD

**Issue by natoverse** [atsid/www.atsid.com#56]
The current build/push to staging is a bit wonky. It will publish PRs against master, but should only be publishing master after the PR is merged. As is, the inclusion of PRs can cause mixed resources on the stage site.

One solution could be to set up a third environment for PRs so they can be tested but not automatically  influence what is available for review on stage, which should only be master right before sending to live.

**Comment by bmathews** [comment]
There's a `[[ "${TRAVIS_PULL_REQUEST}" == 'false' ]]` check that I _think_ can be used to identify the difference between a PR against master vs normal commits/merges.

**Comment by natoverse** [comment]
I think this is working fine as is. It _does_ publish every PR, meaning that multiple PRs can overwrite each other, but realistically the activity level is low enough that this is not likely to happen often. On the other hand, being able to get a PR reviewed before merging to master is pretty valuable, so the current behavior is preferable. The ideal situation would be to spin up a new environment for every PR, but that's just not worth the effort right now.
