### ISSUE TITLE
Audit responsive behavior

### ISSUE THREAD

**Issue by bmathews** [atsid/www.atsid.com#7]

**Comment by TereseV** [comment]
![img_7826](https://cloud.githubusercontent.com/assets/12399802/9412941/dfb89dd0-47fc-11e5-93bc-6498bfd5e057.PNG)
![img_7827](https://cloud.githubusercontent.com/assets/12399802/9412940/dfb818d8-47fc-11e5-8938-2ea6632a69d4.PNG)

Not sure what is happening with this section, but we have 2 alternatives:
- have the image (at a decent size) appear before the text so we only have one column
- correct the sizing for the image and keep it in the same row as the section title, change the paragraph below to fit the width of those
Which one will be easier in our timeframe?

**Comment by bingles** [comment]
Going to hide these images temporarily until a v2 release.
