### ISSUE TITLE
Fix HRM direct listings

### ISSUE THREAD

**Issue by natoverse** [atsid/www.atsid.com#70]
Kimono API "expired" after several days of no positions in Systems, so new posting are not being harvested from HRM and displayed.

**Comment by bmathews** [comment]
@natoverse I can't remember if/when/how I transferred ownership of that scraper, but let me know if there's anything you need from me!

**Comment by natoverse** [comment]
Thanks @bmathews - I have a Kimono account, so I was just going to recreate it. If you are actually able to export or otherwise transfer that would be great.

**Comment by bmathews** [comment]
I _think_ I changed the password and sent @Ken-2scientists the credentials a while back. Doesn't look like I'm able to log in anymore.

**Comment by natoverse** [comment]
Restarted crawler
