### ISSUE TITLE
Add section where we can host press releases

### ISSUE THREAD

**Issue by natoverse** [atsid/www.atsid.com#84]
We can put them in the assets/files folder, but we'll need a landing page of some sort where they can be linked with a brief blurb. Personally, I'd rather not have "media" or "press" be a main nav element since it is more traditional than we're going for with this site. However, linking from other pages to a press page would work. Linking from the "contact" or "about" pages seems appropriate.

**Comment by Ken-2scientists** [comment]
I think we should ask ourselves whether press releases are effective at driving attention or interest first. If there's evidence that they drive attention our way, then it's worth hosting them. Possibly in a 'news' sub area under 'about'?

**Comment by natoverse** [comment]
They are going to be created/released anyway, so it seems sensible to archive them on our site. If we do, we may get some SEO benefit by having additional indexable content that features our work (but we may need to craft HTML versions of them).

**Comment by mike-yencha** [comment]
The only issue I can see with press releases being hosted on a company's
website is how they are dated.  If there isn't a fairly consistent stream
of relevant or "news worthy" content, the older releases can begin to look
"dusty".  You don't want to be seen as showcasing yesterday's news with
nothing current.

Mike

On Fri, Mar 25, 2016, 6:08 PM Nathan Evans <notifications@github.com> wrote:

> They are going to be created/released anyway, so it seems sensible to
> archive them on our site. If we do, we may get some SEO benefit by having
> additional indexable content that features our work (but we may need to
> craft HTML versions of them).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/atsid/www.atsid.com/issues/84#issuecomment-201542320>
>
-- 
Mike Yencha
Graphics Designer / Special Projects
Applied Technical Systems

mike.yencha@atsid.com
(m) 540-429-3135

**Comment by Luckyshot101** [comment]
I think it is best probably to put it as a link on the footer under the "About" section and create a page similar to the "contract vehicles" page.  @bingles do you think you could put together a quick landing page and then we can post up the press release?

**Comment by Luckyshot101** [comment]
This is the press release that needs to be added.

[Farmed - MAR 2016.pdf](https://github.com/atsid/www.atsid.com/files/206718/Farmed.-.MAR.2016.pdf)

**Comment by natoverse** [comment]
Closing this out since there is no real desire to produce these. From an SEO perspective, case studies are probably just as useful anyway.
