### ISSUE TITLE
Finalize careers listing solution/management

### ISSUE THREAD

**Issue by bmathews** [atsid/www.atsid.com#9]
I whipped up something using kimonolabs.com to turn the hrmdirect page into a consumable API. This works great, but we need to have a discussion about the maintainability and long-term support of this.

**Comment by natoverse** [comment]
Extra pertinent now:

> After almost 2 years of building and growing kimono, we couldn’t be happier to announce that the kimono team is joining Palantir! Read more here.
> 
> Because of our new roles at Palantir, it will not be possible for us to continue providing the publicly available cloud hosted kimono product. Effective 2/29/2016 we will be shutting down the service. From that point forward you will no longer be able to log into kimono services or access any of your data via the website or API endpoints. If you wish to back up or archive your data, the kimono website, service and API endpoints will function normally until 2/29/2016. 
> 
> As part of this transition, we have developed a lightweight version of kimono that runs on your desktop PC, available for download at kimonolabs.com/desktop. The desktop application provides the ability to import your kimono APIs (until 03/31/2016). This function will transfer the APIs themselves including API rules, configuration details like modify results functions and data collection rules/url lists but will not transfer any data – so if it's important that you retain the data your APIs have already collected, please download or archive it using some other method.
> 
> Check out the FAQ for more details.
> 
> Thank you to each of you for supporting kimono over the past two years.
> 
> The Kimono Team

**Comment by bingles** [comment]
@z3roshot has implemented a working solution to kimonolabs using import.io #74 

He has hard coded the api key to keep inline with the previous strategy, but has expressed concern that this is a problem we might need to solve. Any thoughts on this matter @natoverse?

**Comment by natoverse** [comment]
I'm going to call this good for now. I think it's small enough and infrequently changing that we can punt on investing more effort.
